### PR TITLE
Changes to resolve idempotency issues with each run and lint fixes.

### PR DESCRIPTION
**Pull request by justicel**

### CODE REVIEW

**Comment by calvn** [comment]
Nice changes on the PR! However the Travis CI build is failing due to the removal of those resource declarations. I would be great if you could change those test cases to properly check for binary presence.

**Comment by justicel** [comment]
Will do.

**Comment by justicel** [comment]
@cleung2010 Tests should be fixed to removed those invalid test steps.

**Comment by calvn** [comment]
I see a potential problem with one of the changes now that I think about it. 

Removing `sudo rm -f ${consul_replicate::bin_dir}/consul-replicate-${consul_replicate::version}` from the resource "Download consul-replicate binary" will create a 0 byte consul-replicate binary if the download fails (due to timeout, disconnect, etc.). Adding the conditional rm -f command on wget failure will ensure that will not happen.

http://superuser.com/a/484378

I'll add it back on the next commit.

**Comment by justicel** [comment]
The problem is that breaks idempotency because every download will re-download the binary. I would suggest that instead of doing that it could be a test for a zero byte file or similar. I can send a pull request if needed.

**Comment by calvn** [comment]
Sure, you are welcomed to do so!

**Comment by calvn** [comment]
Would something like this work then?

``` puppet
exec { 'Remove zero byte binary if download failed':
    command => "rm -f ${consul_replicate::bin_dir}/consul-replicate-${consul_replicate::version}",
    path    => '/usr/bin:/usr/local/bin:/bin',
    unless  => "if [ ! -s ${consul_replicate::bin_dir}/consul-replicate-${consul_replicate::version} ]; then (exit 1); fi;"
} ->
```

**Comment by justicel** [comment]
Shouldn't need to have a separate definition for this. The wget will overwrite it. I'll add an additional test to the download to re-download if it's zero.

**Pull request merged**
