### PR TITLE
Restart respawning too fast and surpasses respawn limit

### PR DESCRIPTION
**Pull request by calvn**
@ryanbreen please review. It is for NG-3336

### CODE REVIEW

**Comment by ryanbreen** [comment]
Do we ever want it to quit trying to respawn?  If not, the guidance here makes sense: http://serverfault.com/questions/472955/how-to-make-upstart-back-off-rather-than-give-up

**Comment by calvn** [comment]
My thinking is that if we don't quit trying to respawn then monitoring apps such as Sensu will always give false negatives and will not report an issue because it's never in the stopped state. We may get lucky and have that check triggered right when the service is stopped, but I would rather have it stopped if it's a deeper issue after several failed attempts to restart.

**Comment by ryanbreen** [comment]
I wouldn't worry too much about that.  Those are the types of issues that metronome should cover.

**Comment by calvn** [comment]
How would this apply to people not using metronome, or for other upstart services in general? I think that post's reply gave "unlimited restart" as the answer because the OP specifically asked for it in his second point, not necessarily because it's the recommended guidance.

**Comment by ryanbreen** [comment]
I think infinite restart is a reasonable approach as long as something is testing service health.  Things that aren't covered by metronome won't be covered, but I'm fine gambling that'll happen some rare % of the time (and if the service is really restarting infinitely, we will get sensu alerts during the `post-stop exec` window (and you can bump that up to 10 or even 30 seconds if we want to make sure we get sensu alerts more frequently in this case).

**Comment by calvn** [comment]
I actually like that post's exponential sleep. We can make sure that Sensu checks trigger by bumping the `NEW_SLEEP_TIME` max value to be greater than the check interval. In that case we can have indefinite respawn and still trigger monitoring checks.

**Comment by ryanbreen** [comment]
Cool, sounds good to me.

**Pull request merged**
